Added support for new listitem art handling in Jarvis
kodi-czsk/script.module.stream.resolver pull request #41
Opened 2016-09-18 18:55 UTC by zbyna

Z dokumentace:
Starting from 16.0 (Jarvis) all image-related parameters and methods will be depreciated  and ``setArt`` will become the only method for setting ListItem's images.
Úprava je potřebná pro funkčnost:  https://github.com/kodi-czsk/plugin.video.sosac.ph/pull/79

2016-10-14 00:44 UTC, zbyna commented
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kodi-czsk/script.module.stream.resolver/41)*
<!-- Sent from Reviewable.io -->

2016-11-05 23:48 UTC, lubo requested changes

2016-11-05 23:48 UTC, Lubo commented on lib/contentprovider/xbmcprovider.py
> +            if 'art' in item['info'].keys():
Nepotrebujes volat `.keys()`.

2016-11-05 23:48 UTC, Lubo commented on lib/contentprovider/xbmcprovider.py
> +            # new art handling from Jarvis - end
Zbytocny komentar. Komentuj len veci, ktore si to vyzaduju.

2016-11-05 23:48 UTC, Lubo commented on lib/contentprovider/xbmcprovider.py
> +                    # tv serie
AFAIK, thumbnail je nahlad. Z tvojich komentarov to ale vyzera tak, ze `poster` sa pouziva len pre filmy a `thumb` iba pre serialy.

2016-11-06 13:58 UTC, zbyna commented on lib/contentprovider/xbmcprovider.py
> +            # new art handling from Jarvis - end
OK. Občas si připadám jako ve škole :smiling_imp:

2016-11-06 14:00 UTC, zbyna commented on lib/contentprovider/xbmcprovider.py
> +                    # tv serie
Je to přesně tak, nemám rád, když mají všechny epizody  stejnou grafiku v osd.

2016-11-06 14:01 UTC, zbyna commented on lib/contentprovider/xbmcprovider.py
> +            if 'art' in item['info'].keys():
To si musím zkusit. Zřejmě máš pravdu.

2016-11-06 14:08 UTC, lubo commented on lib/contentprovider/xbmcprovider.py
> +                    # tv serie
Pointa je, ze aj film moze mat thumbnails, aj videoklip moze mat poster alebo thumbnails, ...

2016-11-06 14:15 UTC, zbyna commented on lib/contentprovider/xbmcprovider.py
> +                    # tv serie
Dobře tak jinak. Prostě nechci mít v OSD u jednotlivých epizod poster a pro filmy mi poster v OSD vyhovuje. Pokud existuje nějaká jiná cesta jak toho dosáhnout, prostě jsem na ní nepřišel.

2016-11-06 14:28 UTC, Lubo commented on lib/contentprovider/xbmcprovider.py
> +                    # tv serie
Nehovorim o tom. Kod je uplne v poriadku, ja referujem na tie komentare, ktore su podla mna trocha matuce.

2016-11-06 20:52 UTC, closed without merging