CF protection
kodi-czsk/script.module.stream.resolver pull request #51
Opened 2017-01-03 10:40 UTC by bbaronSVK

CF protection

2017-01-03 13:17 UTC, bbaronSVK commented
@Lubo skusal som to na svojom plugine a CF ma nepustil. Je mozne, ze je tam nejaky problem s cookies, alebo UA. Vypocty z JS su spravne, preveroval som to, takze by ta ochrana mala byt prelomena...

2017-01-04 16:13 UTC, bbaronSVK commented
@Lubo Takto to uz funguje, len neviem, ci som to spravne pouzil. Upravil som este aj sosac.py aby to s nim fungovalo a aby sa cookies kesovali. Snad je to teda OK. CF ochranu som skusal na svojom plugine ktory mam tiez na CF a bez problemov mi to s tymto fungovalo.

2017-01-04 17:12 UTC, bbaronSVK commented
Takz este jeden fix. Ak plugin nepouziva cookies, tak ich ani nemozeme pridavat do hlaviciek.

2017-01-04 22:26 UTC, Lubo commented
Do PR v sosaci som ti napisal, ze preco to nemergnem. Ale toto by sa nam v stream resolvery mohlo hodit, preto to tu este nechajme.

2017-01-05 08:33 UTC, bbaronSVK commented
Urcite sa to bude hodit, testoval som to s mojim plugin ktory je tiez cez CF.

2017-01-08 20:43 UTC, rajcz commented
Nepomůže vám toto :) ? http://stackoverflow.com/questions/33247662/how-to-bypass-cloudflare-bot-ddos-protection-in-scrapy

2017-01-08 22:13 UTC, Lubo commented
@bbaronSVK Vies teraz o nejakom z nasich pluginov, kde vieme toto teraz vyuzit ? (Okrem Sosacu). Ze aby sme to mali kde naozaj otestovat.

@rajcz Ani nie.

2017-01-20 10:00 UTC, bbaronSVK commented
@Lubo  vieme to otestovat na cinema-stream - viem tam zapnut rovnaku ochranu ako ma sosac. Bolo by ale lepsie ak by si mi napisal na mail nejaky kontakt na IM, lebo takto by sa to len tazko testovalo.
Budem inak potrebovat tuto verziu pre moj plugin.

2017-01-20 16:05 UTC, bbaronSVK commented
@Lubo neviem ci sa da na githube pozriet email, tak ti ho pre istotu napisem: bbaron@bbaron.sk

2017-01-22 10:44 UTC, lubo requested changes

2017-01-22 10:44 UTC, Lubo commented on addon.xml
> +<addon id="script.module.stream.resolver" name="Stream Resolver" provider-name="Libor Zoubek" version="1.6.49">
Prosim, nebumpuj verziu pluginu, ked robis PR. Co ak by sme chceli vydat rovnaku verziu este predtym, nez sa mergne tento PR ?

2017-01-22 10:44 UTC, Lubo commented on lib/util.py
> +            self.cache = cache
Preco nespravis proste `self.cache = cache` ? Spravilo by to presne to iste.

2017-01-22 10:44 UTC, Lubo commented on lib/util.py
> +            data = cloudflare.solve(url, _cookie_jar, UA)
Tento isty kod tu vidim viackrat, asi by bolo dobre pre neho spravit pomocnu funkciu.

2017-01-22 10:46 UTC, Lubo commented
@bbaronSVK Sorry, ze som sa k tomu dostal az teraz, ale som znacne vytazeny. Testovanie nechavam plne na tebe. Od teba len potrebujem vediet, ze ci tvoj kod funguje ako ma a z mojej strany nemat ziadne pripomienky.

2017-01-22 18:45 UTC, bbaronSVK commented
@Lubo Upravil som podla pripomienok a otestoval som to s ochranou od cloudflare. moj plugin + online-files a sosac s touto verziou fungovali. Ostatne pluginy som netestoval.

2017-01-22 19:31 UTC, lubo approved these changes

2017-01-22 19:32 UTC, merged